language: php

sudo: false

cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/.cache/pip

addons:
  apt:
    packages:
      - python-sphinx
      - enchant

php:
  - 5.6
  - 7.0
  - hhvm

env:
  - SYMFONY_VERSION='3.1.*'

branches:
  only:
    - master
    - /^\d+\.\d+$/

matrix:
  include:
    - php: 5.6
      env:
        - COMPOSER_FLAGS="--prefer-lowest"
        - SYMFONY_VERSION='2.8.*'
    - php: 7.1
      env:
        - SYMFONY_VERSION='3.1.*'
        - PHPUNIT_FLAGS="--coverage-clover=coverage.clover"
        - COVERAGE=true
    - php: 7.1
      env:
        - SYMFONY_VERSION='2.8.*'
    - php: 7.1
      env:
        - SYMFONY_VERSION='3.1.*'
    - php: 7.1
      env:
        - SYMFONY_VERSION='3.2.*'
install:
  - pip install -qr Resources/doc/requirements.txt --user

before_install:
  - sh -c 'if [ "$SYMFONY_VERSION" != "" ]; then composer require --dev --no-update symfony/symfony=$SYMFONY_VERSION; fi;'

before_script:
  - composer update $COMPOSER_FLAGS

script:
  - SYMFONY_DEPRECATIONS_HELPER=weak vendor/bin/phpunit ${PHPUNIT_FLAGS}
  - make -C Resources/doc SPHINXOPTS='-nW' html
  - make -C Resources/doc spelling

after_script:
  - if [[ "$COVERAGE" = true ]]; then wget https://scrutinizer-ci.com/ocular.phar; fi
  - if [[ "$COVERAGE" = true ]]; then php ocular.phar code-coverage:upload --format=php-clover coverage.clover; fi

after_failure:
  - cat /tmp/fos-http-cache-bundle/logs/test.log
