language: php

sudo: false

cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/.cache/pip

addons:
  apt:
    packages:
      - python-sphinx
      - enchant

php:
  - 5.5
  - 5.6
  - 7.0

env:
  - SYMFONY_VERSION='3.2.*'

branches:
  only:
    - master
    - /^\d+\.\d+$/

matrix:
  include:
    - php: 5.4
      env:
        - COMPOSER_FLAGS="--prefer-lowest"
        - SYMFONY_VERSION='2.8.0'
    - php: 5.6
      env:
        - SYMFONY_VERSION='3.2.*'
        - PHPUNIT_FLAGS="--coverage-clover=coverage.clover"
        - COVERAGE=true
        - DOCCHECK=true
    - php: 5.6
      env:
        - SYMFONY_VERSION='2.8.42'
        - FRAMEWORK_EXTRA_VERSION='~3.0'
    - php: 5.6
      env:
        - SYMFONY_VERSION='3.1.*'
        - FRAMEWORK_EXTRA_VERSION='~3.0'
    - php: 5.6
      env:
        - SYMFONY_VERSION='3.2.*'
        - FRAMEWORK_EXTRA_VERSION='~3.0'
    - php: 5.6
      env:
        - SYMFONY_VERSION='3.4.*'
        - PHPUNIT_FLAGS="--group sf34"
        - FRAMEWORK_EXTRA_VERSION='~3.0'
    - php: hhvm
      dist: trusty

install:
  - if [ "$DOCCHECK" = true ]; then pip install -qr Resources/doc/requirements.txt --user; fi

before_install:
  - sh -c 'if [ "$SYMFONY_VERSION" != "" ]; then composer require --dev --no-update symfony/symfony=$SYMFONY_VERSION; fi'
  - sh -c 'if [ "$FRAMEWORK_EXTRA_VERSION" != "" ]; then composer require --dev --no-update sensio/framework-extra-bundle=$FRAMEWORK_EXTRA_VERSION; fi'

before_script:
  - composer update $COMPOSER_FLAGS

script:
  - SYMFONY_DEPRECATIONS_HELPER=weak vendor/bin/simple-phpunit ${PHPUNIT_FLAGS}
  - if [ "$DOCCHECK" = true ]; then make -C Resources/doc SPHINXOPTS='-nW' html; fi
  - if [ "$DOCCHECK" = true ]; then make -C Resources/doc spelling; fi

after_script:
  - if [[ "$COVERAGE" = true ]]; then wget https://scrutinizer-ci.com/ocular.phar; fi
  - if [[ "$COVERAGE" = true ]]; then php ocular.phar code-coverage:upload --format=php-clover coverage.clover; fi

after_failure:
  - cat /tmp/fos-http-cache-bundle/logs/test.log
