language: php

sudo: false

cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/.cache/pip

addons:
  apt:
    packages:
      - python-sphinx
      - enchant

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - hhvm

branches:
  only:
    - master
    - /^\d+\.\d+$/

matrix:
  include:
    - php: 5.4
      env: COMPOSER_FLAGS="--prefer-lowest"
    - php: 5.6
      env:
        - PHPUNIT_FLAGS="--coverage-clover=coverage.clover"
        - COVERAGE=true
    - php: 5.6
      env: SYMFONY_VERSION='2.3.*'
    - php: 5.6
      env:
        - SYMFONY_VERSION='2.4.*'
        - FRAMEWORK_EXTRA_VERSION='~3.0'
    - php: 5.6
      env:
        - SYMFONY_VERSION='2.5.*'
        - FRAMEWORK_EXTRA_VERSION='~3.0'
    - php: 5.6
      env:
        - SYMFONY_VERSION='2.6.*'
        - FRAMEWORK_EXTRA_VERSION='~3.0'
    - php: 5.6
      env:
        - SYMFONY_VERSION='2.7.*'
        - FRAMEWORK_EXTRA_VERSION='~3.0'
    - php: 5.6
      env:
        - SYMFONY_VERSION='2.8.*@dev'
        - FRAMEWORK_EXTRA_VERSION='~3.0'

install:
  - pip install -qr Resources/doc/requirements.txt --user

before_script:
  - sh -c 'if [ "$SYMFONY_VERSION" != "" ]; then composer require --dev --no-update symfony/symfony=$SYMFONY_VERSION; fi;'
  - sh -c 'if [ "$FRAMEWORK_EXTRA_VERSION" != "" ]; then composer require --dev --no-update sensio/framework-extra-bundle=$FRAMEWORK_EXTRA_VERSION; fi;'
  - composer update $COMPOSER_FLAGS

script:
  - SYMFONY_DEPRECATIONS_HELPER=weak phpunit ${PHPUNIT_FLAGS}
  - make -C Resources/doc SPHINXOPTS='-nW' html
  - make -C Resources/doc spelling

after_script:
  - if [[ "$COVERAGE" = true ]]; then wget https://scrutinizer-ci.com/ocular.phar; fi
  - if [[ "$COVERAGE" = true ]]; then php ocular.phar code-coverage:upload --format=php-clover coverage.clover; fi

after_failure:
  - cat /tmp/fos-http-cache-bundle/logs/test.log
